---
# Area
- name: area/github
  color: "72ccf3"
  description: >-
    Changes made to github actions
- name: area/pre-commit
  color: "BC9BE3"
  description: >-
    Changes made to pre-commit hooks
- name: area/ansible
  color: "7BD7E0"
  description: >-
    Changes made to Ansible resources
- name: area/collection
  color: "7A9CF7"
  description: >-
    Changes made to collection resources
- name: area/cloudflare
  color: "7BD7E0"
  description: >-
    Changes made to Cloudflare resources
- name: area/dev
  color: "7BD7E0"
  description: >-
    Changes made to dev resources
- name: area/file
  color: "7BD7E0"
  description: >-
    Changes made to file resources
- name: area/git
  color: "7BD7E0"
  description: >-
    Changes made to Git resources
- name: area/keeper
  color: "7BD7E0"
  description: >-
    Changes made to Keeper resources
- name: area/logging
  color: "7BD7E0"
  description: >-
    Changes made to Logging resources
- name: area/macos
  color: "7BD7E0"
  description: >-
    Changes made to MacOS resources
- name: area/net
  color: "7BD7E0"
  description: >-
    Changes made to network resources
- name: area/str
  color: "7BD7E0"
  description: >-
    Changes made to string resources
- name: area/sys
  color: "7BD7E0"
  description: >-
    Changes made to system resources
- name: area/web
  color: "7BD7E0"
  description: >-
    Changes made to web resources
- name: area/go-mod-sum
  color: "7BD7E0"
  description: >-
    Changes made to go.mod and go.sum

# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"

# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"

# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: question
  description: >-
    Clarification and/or additional information required to move forward
  color: "cc317c"
