name: Lint test for code
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: true
        default: "true"

jobs:
  lint:
    name: Ensure code is properly linted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 5m

      - name: Setup tmate session if any part of the action fails
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
