name: 🎉 Release Binary
on:
  create:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: true
        default: "true"

jobs:
  release:
    name: Build and configure the basic salt test environment
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v2
        with:
          args: "release --rm-dist"
          version: latest

      - name: Get tag
        id: tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: "Update the package found at https://pkg.go.dev"
        run: curl https://proxy.golang.org/github.com/${{ github.repository_owner	}}/${{ github.event.repository.name }}/@v/${{ steps.branch_name.outputs.SOURCE_TAG }}.info

      # - name: Setup tmate session if any part of the action fails
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
